import '../model/course.dart';
import '../model/course_category.dart';
import '../model/section.dart';

class CourseDataProvider {
  //Here I have already created courses & section list which we will we using hence forth

  //Section List
  static List<Section> sectionList = [
    Section("Giới Thiệu", "10 phút"),
    Section("Kĩ thuật xét tính đơn điệu của hàm số", "20 phút"),
    Section("Cực trị hàm số", "30 phút"),
    Section("Giá trị lớn nhất, giá trị nhỏ nhất", "24 phút"),
    Section("Tiệm cận đồ thị hàm số", "23 phút"),
    Section("Đồ thị hàm trùng phương", "32 phút"),
  ];

  //Course List
  static List<Course> courseList = [
    Course(
        "1",
        "Live C - Toán 2k6 Thi THPT",
        "assets/images/course/toan.png",
        "Khóa học luyện thi THPT Quốc gia của thầy Hồ Thức Thuận là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Hồ Thức Thuận",
        "01-Jan-2022",
        4.2,
        false,
        CourseCategory.programming,
        100,
        '2.5 giờ',
        15,
        sectionList,
        50),
    Course(
        "2",
        "Live C - Lý 2k6 Thi THPT",
        "assets/images/course/a2.png",
        "Khóa học luyện thi THPT Quốc gia của thầy Vũ Tuấn Anh là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Vũ Tuấn Anh",
        "01-Apr-2022",
        4.5,
        false,
        CourseCategory.programming,
        50,
        '3 giờ',
        10,
        sectionList,
        50),
    Course(
        "3",
        "Live C - Hóa 2k6 Thi THPT",
        "assets/images/course/a3.png",
        "Khóa học luyện thi THPT Quốc gia của thầy Vũ Tuấn Anh là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Phạm Văn Thuận",
        "01-Mar-2022",
        5,
        false,
        CourseCategory.programming,
        75,
        '2.7 giờ',
        15,
        sectionList,
        50),
    Course(
        "4",
        "Luyện Thi THPT Anh 2k6",
        "assets/images/course/a4.png",
        "Khóa học luyện thi THPT Quốc gia của cô Vũ Mai Phương là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Vũ Mai Phương",
        "01-Jan-2022",
        4,
        false,
        CourseCategory.programming,
        40,
        '5 giờ',
        30,
        sectionList,
        50),
    Course(
        "5",
        "Live C - Văn 2k6 Thi THPT",
        "assets/images/course/a5.png",
        "Khóa học luyện thi THPT Quốc gia của thầy Phạm Minh Nhật là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Phạm Minh Nhật",
        "01-Jan-2022",
        4.5,
        false,
        CourseCategory.programming,
        120,
        '4.3 giờ',
        25,
        sectionList,
        50),
    Course(
        "6",
        "Live C - Sử 2k6 Thi THPT",
        "assets/images/course/a6.png",
        "Khóa học luyện thi THPT Quốc gia của cô Nguyễn Hương Sen là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Nguyễn Hương Sen",
        "01-MAR-2022",
        4.2,
        false,
        CourseCategory.marketing,
        150,
        '4 giờ',
        20,
        sectionList,
        50),
    Course(
        "7",
        "Live C - Địa lý 2k6 Thi THPT",
        "assets/images/course/a7.png",
        "Khóa học luyện thi THPT Quốc gia của cô Vũ Thị Ngọc Phước là một chương trình học tập chuyên sâu được thiết kế dành cho học sinh lớp 12, chuẩn bị cho kỳ thi THPT Quốc gia. Khóa học bao gồm các bài giảng chi tiết, tài liệu học tập phong phú, và các bài kiểm tra đánh giá năng lực thường xuyên.",
        "Vũ Thị Ngọc Phước",
        "01-Jan-2022",
        4.7,
        false,
        CourseCategory.marketing,
        80,
        '4.2 giờ',
        21,
        sectionList,
        50),
    Course(
        "8",
        "How to Increase Sales",
        "assets/images/course/marketing3.png",
        "You're looking for a complete digital marketing course to teach you everything you need to become a digital marketing expert, right?",
        "Effortless Code Learning",
        "01-Apr-2022",
        4.3,
        false,
        CourseCategory.marketing,
        100,
        '4.5 giờ',
        20,
        sectionList,
        50),
    Course(
        "9",
        "Marketing Strategy",
        "assets/images/course/marketing4.png",
        "In this course, you will learn various marketing strategy",
        "Effortless Code Learning",
        "01-June-2022",
        5,
        false,
        CourseCategory.marketing,
        120,
        '3.5 giờ',
        32,
        sectionList,
        50),
    Course(
        "10",
        "Invest Money Wisely",
        "assets/images/course/finance1.png",
        "In this course, you will learn invest money wisely in various categories. Learn basic of capital market, other debt options.",
        "Effortless Code Learning",
        "15-Feb-2022",
        5,
        false,
        CourseCategory.finance,
        100,
        '6 Hours',
        35,
        sectionList,
        50),
    Course(
        "11",
        "Crypto Technical Analysis",
        "assets/images/course/finance2.png",
        "In this course, you will learn thorough crypto technical analysis. It will covers basic understanding on various crypto currencies. Volatility in crypto market.",
        "Effortless Code Learning",
        "15-Feb-2022",
        4.6,
        false,
        CourseCategory.finance,
        90,
        '3 Hours',
        22,
        sectionList,
        50),
    Course(
        "12",
        "All about Crypto",
        "assets/images/course/finance3.png",
        "In this course, you will learn thorough crypto technical analysis. It will covers basic understanding on various crypto currencies. Volatility in crypto market.",
        "Effortless Code Learning",
        "20-Mar-2022",
        4.8,
        false,
        CourseCategory.finance,
        75,
        '3.5 Hours',
        28,
        sectionList,
        50),
  ];
}
